# REMEMBER TO GO THROUGH THIS FILE, PERSONALISING THE SETTINGS

title: Sergii Kharagorgiev
author:
  name: Sergii Kharagorgiev
  github: coolvision
  twitter: sergii_kara

# If you don't have a favicon, change to false.
favicon: false

footer:
  separator: '|'
  content: Ⓒ  Sergii Kharagorgiev
  # Append current year on build
  year: true

baseurl: "" # Use if your site will be located in a subdirectory, e.g. /blog.
url: "" # the base hostname & protocol for your site, e.g. http://example.com

description: blog

# Build settings
markdown: kramdown
#theme: fundamental


# Enable theme compononents
enabled:
  breadcrumbs: true
  # tags: true
  comments: true
  # Enable RSS menu item
  rss: true
  seo: true
  # Share buttons are only on desktop (user use the share menu on mobile).
  social:
    enabled: true
    twitter: true
    facebook: true
    messenger: false
    whatsapp: false

# Get your disquas shortname from the disqus admin panel for your blog.
disqus_shortname: k10v-github-io
# Define the colors for social buttons.
# socialBtnsColor: '#4845DF'
socialBtnsColor: '#000'

bio:
  enabled: false
  heading: Sergii Kharagorgiev
  subheading:
  img_url: /assets/1460828.jpg
  body: >
    I'm a Ukrainian, currently living and working in Estonia. I work as a software engineer, mainly specializing in computer vison & robotics. This site is for my spare time hobby projects.
#Plugins
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate

# Compress Sass for production.
sass:
  style: compressed

# Specifying front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      author: "YOUR NAME"
      comments: true


permalink: pretty

#######
#PLUGIN CONFIG
#######

# Archives
jekyll-archives:
  enabled:
  - year
  - month
  - tags
  layout: 'archive'
  layouts:
    tag: 'tag_page'
    month: month
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

paginate: 20
